feat(demo): Demo visualizer for buffered ranges.
shaka-project/shaka-player pull request #4417
Opened 2022-08-17 10:58 UTC by theodab

You can activate this visualizer UI by using the new
"Buffer Visualizer" button in the overflow menu of the player UI.

2022-08-17 11:53 UTC, avelad requested changes

2022-08-17 11:53 UTC, avelad commented on demo/visualizer.js
> +    const colors = ['#FF0000', '#00FF00', '#0000FF'];
I need a comment to know what each color means

2022-08-17 11:53 UTC, avelad commented on lib/player.js
> +        shaka.util.FakeEvent.EventName.SegmentAppended, data));
This event needs to be documented at the beginning of the player.js

2022-08-17 11:53 UTC, avelad commented on demo/visualizer.js
> +        // If it's not video or audio, either it's text or it's invalid.
why not display the text? If the text is segmented it may be useful to have this information.

2022-08-17 12:08 UTC, avelad commented
Note: I have tested with HLS in Safari and it shows video, not video and audio.

2022-08-18 10:21 UTC, theodab commented
> Note: I have tested with HLS in Safari and it shows video, not video and audio.

That's odd, to see one but not the other. You mean with `streaming.useNativeHlsOnSafari` disabled, right?

2022-08-18 10:25 UTC, avelad commented
> > Note: I have tested with HLS in Safari and it shows video, not video and audio.
> 
> That's odd, to see one but not the other. You mean with `streaming.useNativeHlsOnSafari` disabled, right?

`streaming.useNativeHlsOnSafari = true`

2022-08-18 19:55 UTC, theodab commented
> > > Note: I have tested with HLS in Safari and it shows video, not video and audio.
> > 
> > 
> > That's odd, to see one but not the other. You mean with `streaming.useNativeHlsOnSafari` disabled, right?
> 
> `streaming.useNativeHlsOnSafari = true`

Well, the segment appended updates (the pieces of text that show up alongside the colored bars) rely on activity within `StreamingEngine`, so that feature not working properly with native HLS is expected. If anything I'm surprised that it shows video.

2022-08-22 16:07 UTC, avelad approved these changes

2022-08-22 17:31 UTC, merged