chore(HLS): Retired unused error code
shaka-project/shaka-player pull request #4428
Opened 2022-08-19 17:00 UTC by theodab

Now that #2337 has been implemented, the error code HLS_INTERNAL_SKIP_STREAM
is no longer used anywhere in the code.
This retires that error, and also cleans up the code that previously
was responsible for handling that error being fired.

Pre-work for #1936

2022-08-19 20:22 UTC, joeyparrish approved these changes

2022-08-19 20:22 UTC, joeyparrish requested changes
Oh, I approved before I saw the test failures.  Please look into those.  Code looks good otherwise, though.

2022-08-20 01:45 UTC, theodab commented
> Oh, I approved before I saw the test failures. Please look into those. Code looks good otherwise, though.

I fixed the test failures. Turned out to be... something that the compiler really should have caught, annoyingly enough. Oh well.

2022-08-20 03:58 UTC, joeyparrish approved these changes

2022-08-20 03:59 UTC, merged