feat: Adds ChannelCount as a filter to the Player Select Audio Track Method
shaka-project/shaka-player pull request #4552
Opened 2022-10-06 11:02 UTC by jlnabais

Adds channelCount to the Select Audio Track method, this allows for selecting a audio track based on the channel count when the language, codec and role are the same.

ISSUE: https://github.com/shaka-project/shaka-player/issues/4550

2022-10-06 11:25 UTC, avelad commented
Please, sign the CLA. Thanks!

2022-10-06 13:54 UTC, jlnabais commented
> Please, sign the CLA. Thanks!

Done :)

2022-10-06 22:01 UTC, theodab requested changes
Looks good to me otherwise.

2022-10-06 22:01 UTC, theodab commented on lib/player.js
> +   * @param {number=} channelsCount
You should also update the JSDoc above.

2022-10-07 08:18 UTC, jlnabais commented on lib/player.js
> +   * @param {number=} channelsCount
Done.

2022-10-07 09:10 UTC, theodab approved these changes

2022-10-07 09:48 UTC, merged