Add preferredAudioLabel to PlayerConfiguration
shaka-project/shaka-player pull request #4763
Opened 2022-11-28 06:04 UTC by tyrelltle

This PR resolves [#4762](https://github.com/shaka-project/shaka-player/issues/4762).

The change is to add PreferredAudioLabel to player configuration so that host apps can decide the default variant label to choose at very beginning.

2022-11-28 06:39 UTC, avelad requested changes

2022-11-28 06:39 UTC, avelad commented on AUTHORS
> +Koen Romers <koenromers@gmail.com>
Please revert this final file line

2022-11-28 06:39 UTC, avelad commented on CONTRIBUTORS
> +Koen Romers <koenromers@gmail.com>
Please revert this final file line

2022-11-28 06:39 UTC, avelad commented on demo/config.js
> +        .addTextInput_(MessageIds.AUDIO_LANGUAGE, 'preferredAudioLabel')
It is necessary to add a different message since it does not do the same thing as preferredAudioLanguage

2022-11-28 06:40 UTC, avelad commented
Please, fix the lint errors. Thanks!

2022-11-28 21:54 UTC, tyrelltle commented on AUTHORS
> +Koen Romers <koenromers@gmail.com>
updated

2022-11-28 22:00 UTC, tyrelltle commented
@avelad 
Thanks for the comments I have updated accordingly.

One question:
Its added to [v4.4](https://github.com/shaka-project/shaka-player/milestone/26), does it mean the change will not be added to current v4.2.x and v4.3.x ?

What makes a PR to be eligible for getting cherry picked into current release (4.2.x and 4.3.x) ?

Thanks.

2022-11-29 08:29 UTC, avelad approved these changes

2022-11-29 08:55 UTC, theodab approved these changes

2022-11-29 09:30 UTC, merged