ci: run tests in Docker
shaka-project/shaka-player pull request #5440
Opened 2023-07-26 07:53 UTC by tykus160

This PR adds Chromium with webdriver to the Docker image, so it's now possible to run at least some subset of tests using Docker env.
Additionally, Alpine version has been bumped up, so recent version of Chromium can be used.

2023-08-07 16:19 UTC, joeyparrish requested changes

2023-08-08 10:40 UTC, tykus160 commented on build/docker/Dockerfile
> +  bash chromium chromium-chromedriver git nodejs npm openjdk11-jre-headless python3
It's Chromium, so not exactly Chrome. Due to that, `webdriver-installer` is not able to determine browser version. So there are 2 ways:
- install webdriver explicitly in a Docker & provide it via env (as I did)
- make `webdriver-installer` also work with Chromium

I've tried creating symlink from `chromium-browser` to `google-chrome` but unfortunately version format is a bit different & it doesn't work with `webdriver-installer`. For Chrome returning string is `Google Chrome 96.0.4664.110` and for Chromium it's `Chromium 115.0.5790.170`. `webdriver-installer` assumes it's Google Chrome and does `output.trim().split(' ')[2]`.

2023-08-08 10:41 UTC, tykus160 commented on .github/workflows/build-and-test.yaml
> +        run: docker run -v $(pwd):/usr/src --user $(id -u):$(id -g) shaka-player-build python3 build/test.py --quick --browsers ChromeHeadless
Understandable! I just reverted that.

2023-08-08 18:30 UTC, joeyparrish approved these changes

2023-08-08 18:30 UTC, merged