fix: Make UITextDisplayer constructor backward compatible
shaka-project/shaka-player pull request #6532
Opened 2024-05-04 13:12 UTC by MichaelSweden

Keep constructor backward compatible with earlier that had two arguments, i.e. make the new third optional for existing applications.

Fixes https://github.com/shaka-project/shaka-player/issues/6531

2024-05-04 13:13 UTC, MichaelSweden commented
This will make it possible to run existing application that creates an UITextDisplayer object and only supply two arguments to the constructor. A test is added to check this. If the third argument is not given, the old value before PR https://github.com/shaka-project/shaka-player/pull/6477 is used. This fix issue https://github.com/shaka-project/shaka-player/issues/6531.

2024-05-06 05:57 UTC, avelad requested changes

2024-05-06 05:57 UTC, avelad commented on lib/text/ui_text_displayer.js
> +    const updatePeriod = (config && config.captionsUpdatePeriod) ?
We have to detect that we do not have a configuration and show a deprecate message:

```
if (!config || !config.captionsUpdatePeriod) {
  shaka.Deprecate.deprecateFeature(5,
      'UITextDisplayer w/ config',
      'Please migrate from initializing UITextDisplayer with a config.');
}
```

2024-05-06 07:17 UTC, avelad commented on lib/text/ui_text_displayer.js
> +    const updatePeriod = (config && config.captionsUpdatePeriod) ?
I'm going to try to add this to the PR so I can merge it and release 4.8.2 asap.

2024-05-06 08:11 UTC, merged

2024-05-06 08:21 UTC, MichaelSweden commented
Great Álvaro with the deprecate message. I have teested it, ok.
Sorry I was late this morning. I now see that you have commit it and also merge it. I will not take any action.
Thanks!