fix: Support for Zenterio
shaka-project/shaka-player pull request #6717
Opened 2024-05-31 08:23 UTC by tykus160

Few bugfixes to support DT Zenterio platform:
- Zenterio seems to have a problem with the EME onKeyStatus event payload (the key statuses map), where the map key ID comes in as empty. This is not correct based on the EME spec:
https://w3c.github.io/encrypted-media/#dom-mediakeysession-keystatuses
- Add polyfills that are used to fix issues with older webkits, same as for older safari browsers

2024-05-31 16:51 UTC, joeyparrish requested changes

2024-05-31 16:51 UTC, joeyparrish commented on lib/player.js
> +    const isEmptyKeyId = keyIds.length === 1 && keyIds[0] === '';
This seems like a non-standard version of isGlobalStatus above (keyIds[0] == '00').

Could you merge them instead?  Then any application reading key statuses will see a recognizable key that is not specific to this platform.

Maybe something like:

```js
let keyIds = Object.keys(keyStatusMap);

// ...

if (keyIds.length == 1 && keyIds[0] == '') {
  keyStatusMap = {'00': keyStatusMap['']};
  keyIds = ['00'];
}

const isGlobalStatus = ...
```

2024-06-03 08:40 UTC, avelad approved these changes

2024-06-03 17:06 UTC, joeyparrish approved these changes

2024-06-03 17:07 UTC, merged