feat(Stats): Add `manifestGapCount` to stats
shaka-project/shaka-player pull request #6804
Opened 2024-06-12 09:48 UTC by tykus160

Resolves #6789

2024-06-12 09:50 UTC, avelad requested changes

2024-06-12 09:50 UTC, avelad commented on externs/shaka/manifest.js
> + *   discontinuities found between periods. For HLS, it is a number of EXT-X-GAP
You should add `GAP=YES`.

2024-06-12 09:50 UTC, avelad commented on externs/shaka/player.js
> + *   discontinuities found between periods. For HLS, it is a number of EXT-X-GAP
You should add `GAP=YES`.

2024-06-12 10:24 UTC, tykus160 commented on externs/shaka/manifest.js
> + *   discontinuities found between periods. For HLS, it is a number of EXT-X-GAP
Done!

2024-06-12 10:24 UTC, tykus160 commented on externs/shaka/player.js
> + *   discontinuities found between periods. For HLS, it is a number of EXT-X-GAP
Done!

2024-06-12 15:31 UTC, avelad approved these changes

2024-06-13 07:40 UTC, theodab approved these changes

2024-06-13 07:41 UTC, merged