fix: Add null check for current reference
shaka-project/shaka-player pull request #7184
Opened 2024-08-20 15:51 UTC by willdharris

Resolves https://github.com/shaka-project/shaka-player/issues/7174.

2024-08-20 18:21 UTC, joeyparrish approved these changes

2024-08-20 18:21 UTC, joeyparrish commented
I'm okay with the fix, but we have some consistent test failures.  Looks like some expectations need to be updated.

2024-08-20 18:22 UTC, joeyparrish commented
Or possibly some other test logic needs to be updated.  Not sure.

2024-08-20 21:29 UTC, willdharris commented
@joeyparrish Thanks for the review. I see the common [failing test](https://github.com/shaka-project/shaka-player/blob/c97e689043644a135dbb45c14df1515fa31217ec/test/media/streaming_engine_unit.js#L685). I'll take a look at what is going on there.

2024-08-20 22:48 UTC, joeyparrish commented
@willdharris, I have prepared new releases for v4.10.x and v4.9.x, but I will wait another day to see this get finished and merged.

2024-08-21 06:53 UTC, avelad requested changes

2024-08-21 06:53 UTC, avelad commented on lib/media/streaming_engine.js
> +    if (mediaState.segmentIterator &&
I'd prefer:

```
    const currentSegment = mediaState.segmentIterator ?
        mediaState.segmentIterator.current() : null;

    if (currentSegment) {
      // Something is buffered from the same Stream.  Use the current position
      // in the segment index.  This is updated via next() after each segment is
      // appended.
      return currentSegment;
    } else if (mediaState.lastSegmentReference || bufferEnd) {
```

2024-08-22 03:48 UTC, willdharris commented
I'm still not sure how to resolve the failed test.
@avelad I see you looked into this one in the past. I'm sure it's been a while, but would you have any insight on this one?
https://github.com/shaka-project/shaka-player/blob/c97e689043644a135dbb45c14df1515fa31217ec/test/media/streaming_engine_unit.js#L685

The failing test indicates `appendBuffer` is getting called 10x more than it was before the change with the simulated VOD asset in the test. Updating the expect does resolve the failed test and all others pass, but that 10x change seems excessive and worth looking in to. 
I did run some smoke tests with our DASH Live content and the Low Latency assets from the demo page. With real content, I'm not seeing the excessive calls to `appendBuffer` like in the test. Maybe there is logic in the test that should be updated? I'm not very familiar with the LL feature or these tests, so it will take me more time to get up to speed.

2024-08-22 06:56 UTC, avelad commented
> I'm still not sure how to resolve the failed test. @avelad I see you looked into this one in the past. I'm sure it's been a while, but would you have any insight on this one?
> 
> https://github.com/shaka-project/shaka-player/blob/c97e689043644a135dbb45c14df1515fa31217ec/test/media/streaming_engine_unit.js#L685
> 
> The failing test indicates `appendBuffer` is getting called 10x more than it was before the change with the simulated VOD asset in the test. Updating the expect does resolve the failed test and all others pass, but that 10x change seems excessive and worth looking in to. I did run some smoke tests with our DASH Live content and the Low Latency assets from the demo page. With real content, I'm not seeing the excessive calls to `appendBuffer` like in the test. Maybe there is logic in the test that should be updated? I'm not very familiar with the LL feature or these tests, so it will take me more time to get up to speed.

@theodab / @tykus160 any idea?

2024-08-23 07:45 UTC, theodab commented
The streaming engine tests use a lot of complicated fakes in them. It unfortunately makes those tests difficult to debug. It's possible this is a result of a bug in the `shaka.test.FakeSegmentIndex` class.

2024-08-23 09:05 UTC, avelad commented
With https://github.com/shaka-project/shaka-player/pull/7197 the problem is solved, once it is merged, please rebase from the main branch, thanks!

2024-08-23 13:19 UTC, avelad commented
@willdharris can you rebase the PR? Thanks!

2024-08-23 15:32 UTC, avelad approved these changes

2024-08-23 15:36 UTC, willdharris commented
> With #7197 the problem is solved, once it is merged, please rebase from the main branch, thanks!

@avelad Thanks for your help with the test!

2024-08-23 16:14 UTC, merged

2024-08-29 11:50 UTC, avelad commented
I'm going to revert this change, sorry!

Due to this change, it is being observed that there are many warning logs of the type:
![imagen](https://github.com/user-attachments/assets/e607fbd7-d6c1-4d5c-a052-e02bda8d79fd)
And it breaks some HLS streams causing the downloaded segments to be duplicated, for example: https://cadena100-cope.flumotion.com/chunks.m3u8